{"name": "Search_NO.003_搜索失败", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "self = <test_allure_demo.TestSearchModel object at 0x0000021AF53242B0>\n\n    @allure.story(\"搜索失败\")\n    @allure.title(\"Search_NO.003_搜索失败\")\n    def test_search_fail(self):\n        print(\"search fail\")\n>       raise Exception (\"oops\")\nE       Exception: oops\n\ntest_allure_demo.py:44: Exception"}, "start": 1636897403939, "stop": 1636897403939, "uuid": "774f3280-771a-4d6f-8322-a9afd6651362", "historyId": "15e08dd555bbedf3036278039b7cbd74", "testCaseId": "8e93da0f31e26fa1e8e0276fa8de6f45", "fullName": "test_allure_demo.TestSearchModel#test_search_fail", "labels": [{"name": "story", "value": "搜索失败"}, {"name": "feature", "value": "搜索模块"}, {"name": "suite", "value": "test_allure_demo"}, {"name": "subSuite", "value": "TestSearchModel"}, {"name": "host", "value": "DESKTOP-5N5QG51"}, {"name": "thread", "value": "10984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_demo"}]}